// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQaZure3HpaqY80CkM8LMes82S19SR49E',
    appId: '1:865928383165:web:4f7b796cd9ee6fd89d45d4',
    messagingSenderId: '865928383165',
    projectId: 'car-rental-4f2a1',
    authDomain: 'car-rental-4f2a1.firebaseapp.com',
    storageBucket: 'car-rental-4f2a1.appspot.com',
    measurementId: 'G-C386PF2KRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn9TRkVfCgwsaO-4IbHGVFRRs_Y9sTNLM',
    appId: '1:865928383165:android:8d3791329a560d069d45d4',
    messagingSenderId: '865928383165',
    projectId: 'car-rental-4f2a1',
    storageBucket: 'car-rental-4f2a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS1hfjFDwIXCKz2PRK51oZyRnIoYt6z3c',
    appId: '1:865928383165:ios:658a60a210b6f70c9d45d4',
    messagingSenderId: '865928383165',
    projectId: 'car-rental-4f2a1',
    storageBucket: 'car-rental-4f2a1.appspot.com',
    iosBundleId: 'com.example.carRentalzzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS1hfjFDwIXCKz2PRK51oZyRnIoYt6z3c',
    appId: '1:865928383165:ios:14269ee99f53bb0c9d45d4',
    messagingSenderId: '865928383165',
    projectId: 'car-rental-4f2a1',
    storageBucket: 'car-rental-4f2a1.appspot.com',
    iosBundleId: 'com.example.carRentalzzz.RunnerTests',
  );
}
